ugc-bot-prod-mysql:
  container_name: ugc-bot-prod-mysql
  image: mysql:5.7.9
  volumes:
  - ~/volumes/ugc-bot/prod-mysql/:/var/lib/mysql/
  environment:
  - MYSQL_USER=root
  - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  - MYSQL_DATABASE=ugc_league
  ports:
  - "3306:3306"
  command: mysqld --lower_case_table_names=1

