ugc-bot-prod-mysql:
  container_name: ugc-bot-prod-mysql
  image: mysql:5.7.9
  volumes:
  - ~/volumes/ugc-bot/prod-mysql/:/var/lib/mysql/
  environment:
  - MYSQL_USER=root
  - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  - MYSQL_DATABASE=ugc_league
  ports:
  - "3306:3306"
  command: mysqld --lower_case_table_names=1 --character-set-server=utf8mb4
ugc-bot-prod-mongodb:
  container_name: ugc-bot-prod-mongodb
  image: mongo:3.0.7
  volumes:
  - ~/volumes/ugc-bot/prod-mongodb/:/data/db/
  ports:
  - "27017:27017"
